import { SIN_TABLE_DATA } from "./sin-table";

/**
 * Fixed-point sine, by table lookup.
 *
 * Angles are in STEPS per full turn, not radians and not degrees. 1024 steps
 * means a whole turn is a power of two, so wrapping an angle is a mask rather
 * than a modulo -- no division, no sign correction, and exactly the same
 * result for negative angles as for positive ones.
 *
 * Results are 16.16 fixed point in [-65536, 65536], i.e. [-1.0, 1.0].
 *
 * There is no interpolation and no runtime computation: the table IS the
 * function. Two machines running the same cart get the same sine because they
 * read the same 4096 bytes, not because they round the same way.
 */

/** Angle steps in a full turn. A power of two, so wrapping is a mask. */
export const SIN_STEPS = 1024 as const;

const STEP_MASK = SIN_STEPS - 1;

/** A quarter turn, the offset from sine to cosine. */
const QUARTER = SIN_STEPS / 4;

/**
 * sin(2*pi*i/1024) in 16.16, for i in [0, 1024).
 *
 * Generated by tools/gen-sin.ts; the normative copy is
 * conformance/fixtures/sin1024.bin. Treat as read-only -- it is shared, and
 * writing to it would corrupt every subsequent frame.
 */
export const SIN_TABLE: Int32Array = SIN_TABLE_DATA;

/**
 * Sine of an angle in steps. Any integer angle works, including negative ones
 * and ones outside a single turn.
 *
 * `a & 1023` does the wrapping. Two things make that correct:
 *
 *   - `&` runs ToInt32 first, which reduces the argument modulo 2^32. Since
 *     1024 divides 2^32, that reduction cannot change the angle modulo 1024,
 *     so even an angle near the int32 limit wraps to the right entry.
 *   - The result of `&` on a positive mask is always non-negative, so -1 maps
 *     to 1023 (one step before a full turn) rather than to a negative index.
 *     A `% 1024` would have given -1 here and read off the front of the table.
 *
 * The angle must be an integer; ToInt32 truncates a fractional angle toward
 * zero, which is not a rounding rule this console wants to depend on.
 */
export function fsin(a: number): number {
  return SIN_TABLE[a & STEP_MASK] as number;
}

/** Cosine of an angle in steps: sine a quarter turn ahead. */
export function fcos(a: number): number {
  return fsin(a + QUARTER);
}
